---
# tasks file for ansible-role-rainloop/

- name: Install base packages
  action: apt pkg={{item}} state=present
  with_items:
  - curl
  - php{{ php_version }}-sqlite3
  - php{{ php_version }}-pgsql
  - php{{ php_version }}-mysql
  - php{{ php_version }}-fpm
  - php{{ php_version }}-gd
  - php{{ php_version }}-cli
  - php{{ php_version }}-curl
  - php{{ php_version }}-dom

- name: create directory /srv/www
  file: path=/srv/www/{{rainloop_hostname}} state=directory

- name: set upload_max_filesize to 100M in php.ing
  replace: dest=/etc/php/{{ php_version }}/fpm/php.ini regexp='upload_max_filesize(\s+)(.+)' replace='upload_max_filesize = 100M'
  notify:
    - Restart php-fpm

- name: set post_max_filesize to 100M in php.ing
  replace: dest=/etc/php/{{ php_version }}/fpm/php.ini regexp='post_max_size(\s+)(.+)' replace='post_max_size = 100M'
  notify:
    - Restart php-fpm

- name: check if rainloop is installed
  action: shell test -f /srv/www/{{rainloop_hostname}}/index.php && echo "ok" || echo ""
  register: rainloop_installed

- name: install rainloop uit
  command: chdir=/srv/www/{{rainloop_hostname}} bash -c "curl -s http://repository.rainloop.net/installer.php | php"
  when: rainloop_installed.stdout != "ok"
  notify:
    - reload nginx

- name: Create the nginx configuration for rainloop
  template: src=nginx/rainloop.j2 dest=/etc/nginx/sites-available/{{rainloop_hostname}}
  notify:
   - reload nginx


- name: Create the links to enable rainloop configuration
  file: path=/etc/nginx/sites-enabled/{{rainloop_hostname}} state=link src=/etc/nginx/sites-available/{{rainloop_hostname}}
  notify:
   - reload nginx
